---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/application-set-refresh: "true"
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-apps'
    spec:
      project: default
      source:
        repoURL: https://github.com/SudoAaron/argocd-apps.git
        targetRevision: HEAD
        path: environments/{{cluster}}/apps
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          allowEmpty: false
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 15m
          limit: 5
        syncOptions:
        - Validate=true
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true