---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: homelab
        url: "https://kubernetes.default.svc"
  template:
    metadata:
      name: '{{cluster}}-kps-stack'
    spec:
      project: default
      source:
        chart: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 56.6.2
        helm:
          releaseName: kube-prometheus-stack
          valueFiles:
            - values.yaml
      destination:
        server: '{{url}}'
        namespace: monitoring
