---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-general-tls
  namespace: monitoring
spec:
  secretName: grafana-general-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: grafana.aaronwilliams.dev
  dnsNames:
    - grafana.aaronwilliams.dev
