apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: testapp
  project: default
  source:
    path: apps/test-app
    repoURL: https://github.com/SudoAaron/argocd-apps
    targetRevision: HEAD
